export const PACK_FILES: [
	string,
	string | null,
][] = [
	[
		"mods/gravestone-forge-1.20.1-1.0.35.jar",
		"RYtXKJPr",
	],
	[
		"mods/rebind_narrator-forge-1.20.1-2.0.2.jar",
		"qw2Ls89j",
	],
	[
		"mods/defaultoptions-forge-1.20-18.0.1.jar",
		"WEg59z5b",
	],
	[
		"mods/drippyloadingscreen_forge_3.0.12_MC_1.20.1.jar",
		"v3CYg2V9",
	],
	[
		"mods/rhino-forge-2001.2.3-build.10.jar",
		"sk9knFPE",
	],
	[
		"mods/bulktrade-1.0.0.jar",
		"gM34U4xh",
	],
	[
		"mods/armorchroma-1.2.6.jar",
		"pJnbPs9G",
	],
	[
		"mods/fabric-api-0.92.6+1.11.14+1.20.1.jar",
		"Aqlf1Shp",
	],
	[
		"mods/I18nUpdateMod-3.7.0-all.jar",
		"PWERr14M",
	],
	[
		"mods/Zeta-1.0-30.jar",
		"MVARlG2f",
	],
	[
		"mods/konkrete_forge_1.8.0_MC_1.20-1.20.1.jar",
		"J81TRJWm",
	],
	[
		"mods/Kiwi-1.20.1-Forge-11.10.0.jar",
		"ufdDoWPd",
	],
	[
		"mods/ConnectorExtras-1.11.2+1.20.1.jar",
		"FYpiwiBR",
	],
	[
		"mods/Bookshelf-Forge-1.20.1-20.2.13.jar",
		"uy4Cnpcm",
	],
	[
		"mods/lostcities-modern-tweaks-v1.0.10.jar",
		"HdIQwHGq",
	],
	[
		"mods/geckolib-forge-1.20.1-4.8.2.jar",
		"8BmcQJ2H",
	],
	[
		"mods/difficultylock-1.20.1-4.7.jar",
		"9yvZtixz",
	],
	[
		"mods/skinlayers3d-forge-1.9.2-mc1.20.1.jar",
		"zV5r3pPn",
	],
	[
		"mods/better-selection-1.2.jar",
		"xIpcAYJL",
	],
	[
		"mods/XaeroZoomout-Forge-1.20-1.1.0.jar",
		"T6oqPfxF",
	],
	[
		"mods/DynamicTrees-1.20.1-1.4.7.jar",
		"vdjF5PL5",
	],
	[
		"mods/inventoryhud.forge.1.20.1-3.4.26.jar",
		"Kp2uclYl",
	],
	[
		"mods/fogoverrides-1.20.1-2.3.0.jar",
		"B1vBJNM4",
	],
	[
		"mods/DynamicTreesQuark-1.20.1-2.5.3.jar",
		"9paueCZy",
	],
	[
		"mods/customvillagertrades-forge-20.25.0.jar",
		"nzF0Kr0W",
	],
	[
		"mods/Necronomicon-Forge-1.6.0+1.20.1.jar",
		"P1Kv5EAO",
	],
	[
		"mods/libIPN-forge-1.20-4.0.2.jar",
		"onSQdWhM",
	],
	[
		"mods/CreativeCore_FORGE_v2.12.32_mc1.20.1.jar",
		"OsZiaDHq",
	],
	[
		"mods/kubejs-forge-2001.6.5-build.16.jar",
		"umyGl7zF",
	],
	[
		"mods/movesubtitles-1.1.jar",
		"xoAMN4kp",
	],
	[
		"mods/lootjs-forge-1.20.1-2.13.0.jar",
		"fJFETWDN",
	],
	[
		"mods/entity_texture_features_1.20.1-forge-7.0.6.jar",
		"BVzZfTc1",
	],
	[
		"mods/AttributeFix-Forge-1.20.1-21.0.4.jar",
		"lOOpEntO",
	],
	[
		"mods/EnchantmentDescriptions-Forge-1.20.1-17.1.19.jar",
		"UVtY3ZAC",
	],
	[
		"mods/EMIEnchants-forge-1.19.3-1.20.4-1.0.0.jar",
		"11hKNQb2",
	],
	[
		"mods/supermartijn642configlib-1.1.8-forge-mc1.20.jar",
		"LN9BxssP",
	],
	[
		"mods/Jade-1.20.1-Forge-11.13.2.jar",
		"nvQzSEkH",
	],
	[
		"mods/CutThrough-v8.0.2-1.20.1-Forge.jar",
		"Dk6su9JN",
	],
	[
		"mods/NoChatReports-FORGE-1.20.1-v2.2.2.jar",
		"qQyHxfxd",
	],
	[
		"mods/tacz-1.20.1-1.1.7-release.jar",
		"SzzJttH8",
	],
	[
		"mods/ImmediatelyFast-Forge-1.5.2+1.20.4.jar",
		"5ZwdcRci",
	],
	[
		"mods/oculus-mc1.20.1-1.8.0.jar",
		"GchcoXML",
	],
	[
		"mods/XaerosWorldMap_1.39.12_Forge_1.20.jar",
		"NcUtCpym",
	],
	[
		"resourcepacks/[1.20.1]ProgrammerArtFix-rv3.1.zip",
		"d1nRD7RG",
	],
	[
		"mods/ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar",
		"5WeWGLoJ",
	],
	[
		"mods/global-server-config-forge-1.18.2+-1.0.jar",
		"c5dOxpD8",
	],
	[
		"mods/advancementinfo-1.20-fabric0.83.0-1.4.jar",
		"G1epq3jN",
	],
	[
		"mods/entity_model_features_1.20.1-forge-3.0.7.jar",
		"4I1XuqiY",
	],
	[
		"mods/zombieawareness-1.20.1-1.13.1.jar",
		"mMTOWOaA",
	],
	[
		"mods/Controlling-forge-1.20.1-12.0.2.jar",
		"xv94TkTM",
	],
	[
		"mods/guardvillagers-1.20.1-1.6.15.jar",
		"H1sntfo8",
	],
	[
		"mods/Fastload-Reforged-mc1.20.1-3.4.0.jar",
		"kCpssoSb",
	],
	[
		"mods/balm-forge-1.20.1-7.3.37-all.jar",
		"MBAkmtvl",
	],
	[
		"mods/jei-1.20.1-forge-15.20.0.127.jar",
		"u6dRKJwZ",
	],
	[
		"mods/SpartanShields-1.20.1-forge-3.1.1.jar",
		"W5rjEyqs",
	],
	[
		"mods/melody_forge_1.0.3_MC_1.20.1-1.20.4.jar",
		"CVT4pFB2",
	],
	[
		"mods/sound-physics-remastered-forge-1.20.1-1.5.1.jar",
		"qyVF9oeo",
	],
	[
		"mods/yet_another_config_lib_v3-3.6.6+1.20.1-forge.jar",
		"1eAoo2KR",
	],
	[
		"mods/physics-mod-3.0.14-mc-1.20.1-forge.jar",
		"Xy8aRQKS",
	],
	[
		"mods/embeddium-0.3.31+mc1.20.1.jar",
		"sk9rgfiA",
	],
	[
		"mods/VisualWorkbench-v8.0.1-1.20.1-Forge.jar",
		"kfqD1JRw",
	],
	[
		"mods/smoothscroll-2.1.3.1+1.20.1.jar",
		"CllP7wW0",
	],
	[
		"mods/EnhancedVisuals_FORGE_v1.8.2_mc1.20.1.jar",
		"KjL0jE2w",
	],
	[
		"mods/modernfix-forge-5.25.1+mc1.20.1.jar",
		"nmDcB62a",
	],
	[
		"mods/FastScrolling-2.0.1.jar",
		"JZKbCCSk",
	],
	[
		"mods/Patchouli-1.20.1-84.1-FORGE.jar",
		"nU0bVIaL",
	],
	[
		"mods/taczdd-0.1.1.jar",
		"wJXFReaO",
	],
	[
		"mods/emi-1.1.22+1.20.1+forge.jar",
		"fRiHVvU7",
	],
	[
		"mods/YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar",
		"HaaH232J",
	],
	[
		"mods/SpartanWeaponry-1.20.1-forge-3.1.3-all.jar",
		"icU5P2Mk",
	],
	[
		"mods/IMBlocker-5.4.6-forge+1.17-1.20.4.jar",
		"WMDesFsZ",
	],
	[
		"mods/AgeingSpawners-1.20.1-2.0.0.jar",
		"npA68nxC",
	],
	[
		"mods/coroutil-forge-1.20.1-1.3.7.jar",
		"rLLJ1OZM",
	],
	[
		"mods/sophisticatedbackpacks-1.20.1-3.24.12.1411.jar",
		"TyCTlI4b",
	],
	[
		"mods/letmedespawn-1.20.x-forge-1.5.0.jar",
		"vE2FN5qn",
	],
	[
		"mods/AI-Improvements-1.20-0.5.2.jar",
		"DSVgwcji",
	],
	[
		"mods/numismatic-overhaul-0.2.18+1.20.jar",
		"ZXm8hVxN",
	],
	[
		"mods/BetterModsButton-v8.0.2-1.20.1-Forge.jar",
		"KUZAAwdD",
	],
	[
		"mods/notenoughanimations-forge-1.10.6-mc1.20.1.jar",
		"MPCX6s5C",
	],
	[
		"mods/zume-1.2.0.jar",
		"o6qsdrrQ",
	],
	[
		"mods/clienttweaks-forge-1.20.1-11.1.3.jar",
		"vPNqo58Q",
	],
	[
		"mods/Connector-1.0.0-beta.47+1.20.1.jar",
		"u58R1TMW",
	],
	[
		"mods/chat_heads-0.14.2-forge-1.20.jar",
		"Wb5oqrBJ",
	],
	[
		"mods/architectury-9.2.14-forge.jar",
		"lhGA9TYQ",
	],
	[
		"mods/owo-lib-0.11.2+1.20.jar",
		"ccKDOlHs",
	],
	[
		"mods/chatanimation-1.0.5.jar",
		"DnNYdJsx",
	],
	[
		"mods/lcchatlogfilter-1.1.jar",
		"6WLir0AT",
	],
	[
		"mods/starlight-1.1.2+forge.1cda73c.jar",
		"iRfIGC1s",
	],
	[
		"mods/cherishedworlds-forge-6.1.7+1.20.1.jar",
		"3azQ6p0W",
	],
	[
		"mods/DynamicTreesBOP-1.20.1-3.3.3.jar",
		"8QHjGuhP",
	],
	[
		"mods/GlitchCore-forge-1.20.1-0.0.1.1.jar",
		"s3dmwKy5",
	],
	[
		"mods/curios-forge-5.14.1+1.20.1.jar",
		"vvuO3ImH",
	],
	[
		"mods/fast-ip-ping-mc1.19.4-forge-v1.0.1.jar",
		"9mtu0sUO",
	],
	[
		"mods/hardcorerevival-forge-1.20.1-12.0.9.jar",
		"HqKoXaXz",
	],
	[
		"mods/lostcities-1.20-7.4.6.jar",
		"8VDCUS3b",
	],
	[
		"mods/taczaddon-1.20.1-1.1.6.jar",
		"3Ihyt5WL",
	],
	[
		"mods/globalpacks-forge-1.20.1-19.3.7.jar",
		"NRLPy2mk",
	],
	[
		"mods/BadOptimizations-2.4.0-1.20.1.jar",
		"g96Z4WVZ",
	],
	[
		"mods/BiomesOPlenty-forge-1.20.1-19.0.0.96.jar",
		"HXF82T3G",
	],
	[
		"mods/chloride-FORGE-mc1.20.1-v1.7.2.jar",
		"yD9qW65f",
	],
	[
		"mods/CustomSkinLoader_ForgeV2-14.26.1.jar",
		"idMHQ4n2",
	],
	[
		"mods/smsn-forge-1.3.5-1.20.1.jar",
		"oXzIQwRj",
	],
	[
		"mods/Hide-Key-Binding-1.0.0.7.jar",
		"mWovtWTo",
	],
	[
		"mods/sodiumdynamiclights-forge-1.0.10-1.20.1.jar",
		"PxQSWIcD",
	],
	[
		"mods/kotlinforforge-4.12.0-all.jar",
		"ordsPcFz",
	],
	[
		"mods/ferritecore-6.0.1-forge.jar",
		"uXXizFIs",
	],
	[
		"mods/open-parties-and-claims-forge-1.20.1-0.25.8.jar",
		"gF3BGWvG",
	],
	[
		"mods/cloth-config-11.1.136-forge.jar",
		"9s6osm5g",
	],
	[
		"mods/Xaeros_Minimap_25.2.10_Forge_1.20.jar",
		"1bokaNcj",
	],
	[
		"mods/enchanted_arsenal-1.0.1-forge-1.20.1.jar",
		"iFRF5kc2",
	],
	[
		"mods/DynamicTreesPlus-1.20.1-1.2.1.jar",
		"qaO9Dqpu",
	],
	[
		"mods/Neat-1.20.1-41-FORGE.jar",
		"Ins7SzzR",
	],
	[
		"mods/sophisticatedcore-1.20.1-1.2.107.1240.jar",
		"nmoqTijg",
	],
	[
		"mods/emiffect-forge-1.1.2+mc1.20.1.jar",
		"705gWllI",
	],
	[
		"mods/durabilitytooltip-1.1.6-forge-mc1.20.jar",
		"smUP7V3r",
	],
	[
		"mods/TerraBlender-forge-1.20.1-3.0.1.10.jar",
		"kkmrDlKT",
	],
	[
		"mods/chattools-1.20.1-v2.3.11.jar",
		"pbnlOdwp",
	],
	[
		"mods/Searchables-forge-1.20.1-1.0.3.jar",
		"fuuu3xnx",
	],
	[
		"mods/ironfurnaces-1.20.1-4.1.6.jar",
		"yPlaLxD1",
	],
	[
		"mods/almanac-1.20.x-forge-1.0.2.jar",
		"Gi02250Z",
	],
	[
		"mods/TES-forge-1.20.1-1.6.1.jar",
		"4A86JsDZ",
	],
	[
		"mods/fancymenu_forge_3.7.0_MC_1.20.1.jar",
		"Wq5SjeWM",
	],
	[
		"mods/InventoryProfilesNext-forge-1.20-1.10.14.jar",
		"O7RBXm3n",
	],
	[
		"mods/Quark-4.0-462.jar",
		"qnQsVE2z",
	],
	[
		"mods/PuzzlesLib-v8.1.33-1.20.1-Forge.jar",
		"QAGBst4M",
	],
	[
		"resourcepacks/Better-Old-Netherack-1.0.zip",
		"i05p3PCW",
	],
	[
		"mods/appleskin-forge-mc1.20.1-2.5.1.jar",
		"EsAfCjCV",
	],
	[
		"mods/jecharacters-1.20.1-forge-4.6.1.jar",
		"I7k4B65h",
	],
	[
		"mods/collective-1.20.1-8.13.jar",
		"e0M1UDsY",
	],
];

export const PACK_SIDES: Record<string, string> = {
	"11hKNQb2": "unsupported",
	"1bokaNcj": "optional",
	"1eAoo2KR": "optional",
	"3Ihyt5WL": "required",
	"3azQ6p0W": "unsupported",
	"4A86JsDZ": "optional",
	"4I1XuqiY": "unsupported",
	"5WeWGLoJ": "optional",
	"5ZwdcRci": "unsupported",
	"6WLir0AT": "required",
	"705gWllI": "unsupported",
	"8BmcQJ2H": "optional",
	"8QHjGuhP": "required",
	"8VDCUS3b": "required",
	"9mtu0sUO": "unsupported",
	"9paueCZy": "required",
	"9s6osm5g": "optional",
	"9yvZtixz": "required",
	Aqlf1Shp: "required",
	B1vBJNM4: "optional",
	BVzZfTc1: "unsupported",
	CVT4pFB2: "unknown",
	CllP7wW0: "unsupported",
	DSVgwcji: "required",
	Dk6su9JN: "unsupported",
	DnNYdJsx: "unsupported",
	EsAfCjCV: "optional",
	FYpiwiBR: "optional",
	G1epq3jN: "unsupported",
	GchcoXML: "unsupported",
	Gi02250Z: "required",
	H1sntfo8: "required",
	HXF82T3G: "required",
	HaaH232J: "unsupported",
	HdIQwHGq: "required",
	HqKoXaXz: "required",
	I7k4B65h: "unsupported",
	Ins7SzzR: "unsupported",
	J81TRJWm: "optional",
	JZKbCCSk: "unsupported",
	KUZAAwdD: "unsupported",
	KjL0jE2w: "required",
	Kp2uclYl: "unsupported",
	LN9BxssP: "optional",
	MBAkmtvl: "optional",
	MPCX6s5C: "unsupported",
	MVARlG2f: "required",
	NRLPy2mk: "optional",
	NcUtCpym: "optional",
	O7RBXm3n: "unsupported",
	OsZiaDHq: "optional",
	P1Kv5EAO: "required",
	PWERr14M: "unsupported",
	PxQSWIcD: "unsupported",
	QAGBst4M: "optional",
	RYtXKJPr: "required",
	SzzJttH8: "required",
	T6oqPfxF: "unsupported",
	TyCTlI4b: "required",
	UVtY3ZAC: "optional",
	W5rjEyqs: "required",
	WEg59z5b: "unsupported",
	WMDesFsZ: "unsupported",
	Wb5oqrBJ: "unsupported",
	Wq5SjeWM: "optional",
	Xy8aRQKS: "unsupported",
	ZXm8hVxN: "required",
	c5dOxpD8: "required",
	ccKDOlHs: "required",
	d1nRD7RG: "unsupported",
	e0M1UDsY: "optional",
	fJFETWDN: "required",
	fRiHVvU7: "optional",
	fuuu3xnx: "unsupported",
	g96Z4WVZ: "unsupported",
	gF3BGWvG: "required",
	gM34U4xh: "unsupported",
	i05p3PCW: "unsupported",
	iFRF5kc2: "required",
	iRfIGC1s: "optional",
	icU5P2Mk: "required",
	idMHQ4n2: "unsupported",
	kCpssoSb: "optional",
	kfqD1JRw: "required",
	kkmrDlKT: "required",
	lOOpEntO: "required",
	lhGA9TYQ: "required",
	mMTOWOaA: "required",
	mWovtWTo: "unsupported",
	nU0bVIaL: "required",
	nmDcB62a: "optional",
	nmoqTijg: "required",
	npA68nxC: "required",
	nvQzSEkH: "optional",
	nzF0Kr0W: "required",
	o6qsdrrQ: "unsupported",
	onSQdWhM: "unsupported",
	ordsPcFz: "optional",
	pJnbPs9G: "unsupported",
	pbnlOdwp: "unsupported",
	qQyHxfxd: "optional",
	qaO9Dqpu: "required",
	qnQsVE2z: "required",
	qw2Ls89j: "unsupported",
	qyVF9oeo: "optional",
	rLLJ1OZM: "required",
	s3dmwKy5: "required",
	sk9knFPE: "optional",
	sk9rgfiA: "unsupported",
	smUP7V3r: "unsupported",
	u58R1TMW: "optional",
	u6dRKJwZ: "optional",
	uXXizFIs: "optional",
	ufdDoWPd: "optional",
	umyGl7zF: "optional",
	uy4Cnpcm: "required",
	v3CYg2V9: "unsupported",
	vE2FN5qn: "required",
	vPNqo58Q: "unsupported",
	vdjF5PL5: "required",
	vvuO3ImH: "required",
	wJXFReaO: "unsupported",
	xIpcAYJL: "unsupported",
	xoAMN4kp: "unsupported",
	xv94TkTM: "unsupported",
	yD9qW65f: "unsupported",
	yPlaLxD1: "required",
	zV5r3pPn: "unsupported",
};

export const PACK_SLUGS: Record<string, string> = {
	"11hKNQb2": "emienchants",
	"1bokaNcj": "xaeros-minimap",
	"1eAoo2KR": "yacl",
	"3Ihyt5WL": "taczaddon",
	"3azQ6p0W": "cherished-worlds",
	"4A86JsDZ": "tslatentitystatus",
	"4I1XuqiY": "entity-model-features",
	"5WeWGLoJ": "forge-config-screens",
	"5ZwdcRci": "immediatelyfast",
	"6WLir0AT": "lostcitiesfilter",
	"705gWllI": "emiffect",
	"8BmcQJ2H": "geckolib",
	"8QHjGuhP": "dynamic-trees-biomes-o-plenty",
	"8VDCUS3b": "the-lost-cities",
	"9mtu0sUO": "fast-ip-ping",
	"9paueCZy": "dynamic-trees-quark",
	"9s6osm5g": "cloth-config",
	"9yvZtixz": "difficulty-lock",
	Aqlf1Shp: "forgified-fabric-api",
	B1vBJNM4: "fogoverrides",
	BVzZfTc1: "entitytexturefeatures",
	CVT4pFB2: "melody",
	CllP7wW0: "smooth-scroll",
	DSVgwcji: "ai-improvements",
	Dk6su9JN: "cut-through",
	DnNYdJsx: "chatanimation",
	EsAfCjCV: "appleskin",
	FYpiwiBR: "connector-extras",
	G1epq3jN: "advancementinfo",
	GchcoXML: "oculus",
	Gi02250Z: "almanac",
	H1sntfo8: "guard-villagers",
	HXF82T3G: "biomes-o-plenty",
	HaaH232J: "yeetus-experimentus",
	HdIQwHGq: "lost-cities-modern-tweaks",
	HqKoXaXz: "hardcore-revival",
	I7k4B65h: "justenoughcharacters",
	Ins7SzzR: "neat",
	J81TRJWm: "konkrete",
	JZKbCCSk: "fast-scrolling",
	KUZAAwdD: "better-mods-button",
	KjL0jE2w: "enhancedvisuals",
	Kp2uclYl: "inventoryhudplus",
	LN9BxssP: "supermartijn642s-config-lib",
	MBAkmtvl: "balm",
	MPCX6s5C: "not-enough-animations",
	MVARlG2f: "zeta",
	NRLPy2mk: "globalpacks",
	NcUtCpym: "xaeros-world-map",
	O7RBXm3n: "inventory-profiles-next",
	OsZiaDHq: "creativecore",
	P1Kv5EAO: "necronomicon",
	PWERr14M: "i18nupdatemod",
	PxQSWIcD: "sodium-dynamic-lights",
	QAGBst4M: "puzzles-lib",
	RYtXKJPr: "gravestone-mod",
	SzzJttH8: "timeless-and-classics-zero",
	T6oqPfxF: "xaero-zoomout",
	TyCTlI4b: "sophisticated-backpacks",
	UVtY3ZAC: "enchantment-descriptions",
	W5rjEyqs: "spartan-shields",
	WEg59z5b: "default-options",
	WMDesFsZ: "imblocker-original",
	Wb5oqrBJ: "chat-heads",
	Wq5SjeWM: "fancymenu",
	Xy8aRQKS: "physicsmod",
	ZXm8hVxN: "numismatic-overhaul",
	c5dOxpD8: "global-server-config",
	ccKDOlHs: "owo-lib",
	d1nRD7RG: "programmer-art-fix",
	e0M1UDsY: "collective",
	fJFETWDN: "lootjs",
	fRiHVvU7: "emi",
	fuuu3xnx: "searchables",
	g96Z4WVZ: "badoptimizations",
	gF3BGWvG: "open-parties-and-claims",
	gM34U4xh: "bulk-villager-trading",
	i05p3PCW: "better-old-netherrack",
	iFRF5kc2: "enchanted-arsenal",
	iRfIGC1s: "starlight-forge",
	icU5P2Mk: "spartan-weaponry",
	idMHQ4n2: "customskinloader",
	kCpssoSb: "fastload",
	kfqD1JRw: "visual-workbench",
	kkmrDlKT: "terrablender",
	lOOpEntO: "attributefix",
	lhGA9TYQ: "architectury-api",
	mMTOWOaA: "zombie-awareness",
	mWovtWTo: "hide-key-binding",
	nU0bVIaL: "patchouli",
	nmDcB62a: "modernfix",
	nmoqTijg: "sophisticated-core",
	npA68nxC: "ageing-spawners",
	nvQzSEkH: "jade",
	nzF0Kr0W: "custom-villager-trades",
	o6qsdrrQ: "zume",
	onSQdWhM: "libipn",
	ordsPcFz: "kotlin-for-forge",
	pJnbPs9G: "armor-chroma-for-fabric",
	pbnlOdwp: "chat-tools",
	qQyHxfxd: "no-chat-reports",
	qaO9Dqpu: "dynamictreesplus",
	qnQsVE2z: "quark",
	qw2Ls89j: "rebind-narrator",
	qyVF9oeo: "sound-physics-remastered",
	rLLJ1OZM: "coroutil",
	s3dmwKy5: "glitchcore",
	sk9knFPE: "rhino",
	sk9rgfiA: "embeddium",
	smUP7V3r: "durability-tooltip",
	u58R1TMW: "connector",
	u6dRKJwZ: "jei",
	uXXizFIs: "ferrite-core",
	ufdDoWPd: "kiwi",
	umyGl7zF: "kubejs",
	uy4Cnpcm: "bookshelf-lib",
	v3CYg2V9: "drippy-loading-screen",
	vE2FN5qn: "lmd",
	vPNqo58Q: "client-tweaks",
	vdjF5PL5: "dynamictrees",
	vvuO3ImH: "curios",
	wJXFReaO: "tacz-tes-compat",
	xIpcAYJL: "better-selection",
	xoAMN4kp: "move-subtitles",
	xv94TkTM: "controlling",
	yD9qW65f: "chloride",
	yPlaLxD1: "iron-furnaces",
	zV5r3pPn: "3dskinlayers",
};
